/**
* This file was automatically generated by @cosmwasm/ts-codegen@0.19.0.
* DO NOT MODIFY IT BY HAND. Instead, modify the source JSONSchema file,
* and run the @cosmwasm/ts-codegen generate command to regenerate this file.
*/

export type Addr = string;
export type Uint128 = string;
export interface InstantiateMsg {
  blue_token_address: Addr;
  red_token_address: Addr;
  token_address: Addr;
  total_supply: Uint128;
}
export type ExecuteMsg = {
  receive: Cw20ReceiveMsg;
} | {
  claim: {};
};
export type Binary = string;
export interface Cw20ReceiveMsg {
  amount: Uint128;
  msg: Binary;
  sender: string;
}
export type QueryMsg = {
  supply_info: {};
} | {
  deposit_info: {
    address: Addr;
  };
};
export interface DepositInfoResponse {
  blue: Uint128;
  red: Uint128;
}
export interface SupplyInfoResponse {
  claimed_supply: Uint128;
  remaining_supply: Uint128;
  total_supply: Uint128;
}